package org.dasein.cloud.quotas;

/**
 * User: mgulimonov
 * Date: 17.11.2014
 */
public enum CloudResourceType {

    INSTANCE, LAUNCH_CONFIG, VOLUME, SNAPSHOT, IMAGE, FIREWALL, LOAD_BALANCER, NETWORK,
    SUBNET, INTERNET_GATEWAY, ROUTE_TABLE, ROUTE, IP_ADDRESS, ALARM, AUTO_SCALING_GROUP, SSL_CERTIFICATE

}
